### PR TITLE
Use illuminate/support: 4.*

### LINKED ISSUE #3: Update Illuminate/Support
Is there any reason why `illuminate/support` can't be updated to support Laravel 4.2.11?

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #3 - I'm trying this out first, but I can't see any changes that'll break it.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Bump.

**Comment by freddiecoleman** [comment]
Still needs fixing!

**Comment by jbrooksuk** [comment]
Just needs a merge :(

**Comment by kenmoini** [comment]
Fix'd ...8^)

**Comment by jbrooksuk** [comment]
:beers:

**Pull request merged**
